### ISSUE TITLE
Square brackets in file name

### ISSUE THREAD

**Issue by eqagunn** [DavidDeprost/mpv-autosub#3] opened 2019-08-05 09:56 UTC
If square brackets are present in the filename, subtitles won't get downloaded.
Example using subliminal in terminal:

`matz@neon:~/Desktop$ subliminal download -l en "Game.of.Thrones.S08E03.720p.WEB.x265-MiNX[eztv].mkv"`
`1 video collected / 0 video ignored / 0 error`
`Downloaded 0 subtitle`

You could replace all occurrences of square brackets in filename string with dashes, and then send it to subliminal:  

`matz@neon:~/Desktop$ subliminal download -l en "Game.of.Thrones.S08E03.720p.WEB.x265-MiNX-eztv-.mkv"`
`Collecting videos  [####################################]  100%  `                                                   
`1 video collected / 0 video ignored / 0 error`
`Downloading subtitles  [####################################]  100%   `                                                  
`Downloaded 1 subtitle`

**Comment by DavidDeprost** [comment] 2019-08-05 11:00
I'm sorry but I can't reproduce your issue. I downloaded the same Game of Thrones file, but the subtitle download works flawlessly on my Debian Linux system. What OS are you on? I have not yet tested this script on anything other than Linux, maybe it is time to do so ...

**Comment by eqagunn** [comment] 2019-08-05 19:44
Hi David.

I was no longer getting the same pattern when I tried to reproduce. I got the completely opposite results. Now it downloaded if square brackets were present, and it didn't if they weren't. Which made no sense so I went to make some deeper testing.

What I was able to realize is the following...
When using subliminal in terminal, if the file name given matches the file that actually exists in the working directory, subliminal will look into its title metadata, and if it exists it will look for subtitles based on title name instead of the file name.

The reason I got the opposite results is that I had that file renamed in the meantime. And the reason it wouldn't download the subtitles if the filename was matched with an actual file is because the title of the file was "MiNX - Game.of.Thrones.S08E03.720p.WEB.x265-MiNX".

If I were to copy the filename to another file which doesn't have title metadata set it would downloaded subtitles regardless whether square brackets were present or not.

Or so I thought...

As I was about to submit this reply, I went to test this with another file that had title metadata set to "PSArips.com | Event.Horizon.1997.REMASTERED.1080p.10bit.BluRay.6CH.x265.HEVC-PSA" and to my surprise, subtitles were downloaded without a problem.

Which makes my previous observations untrue.

The only conclusion I had is that it had to do something with that specific file I initially encountered problems with. So I ended up pulling it through mkvtoolnix multiplexer without changing any of the values, and the new output didn't have any before-mentioned problems, as expected.

I believe we weren't testing on the same file as mine seems to be a re-encode by torrentgalaxy. Their watermark is present from 2nd to 7th second of the video. If you would like to to test it yourself, you can get it from torrentz2.eu by searching for "game of thrones". At the moment, it's the third result from the list. Torrent size is 415 MB. md5sum returns 5499d03c0c96b04ff4861904da8ee81c.

Kind regards and thanks for the script,
Matej

**Comment by DavidDeprost** [comment] 2019-08-05 21:55
Ok, no worries, thanks for the elaborate clarification!

If I understand correctly, there are no further problems, so I'll close this issue.

**Closed by DavidDeprost** 2019-08-05 21:55 UTC

**Comment by DavidDeprost** [comment] 2019-08-06 13:58
I ended up testing this file anyway out of curiosity, and it appears the problem stems from the fact this file has embedded subtitles that are **inactivated** by default. Subliminal still detects their presence, and aborts downloading subtitles because they are already present.

Updated the script with a fix and --debug mode, so it should work on your original file now.

**Comment by eqagunn** [comment] 2019-08-07 04:28
Nicely done! This greatly increases the effectiveness of the script.

What do you think on using `utils.subprocess()` like [vayan](https://github.com/vayan/autosub-mpv/blob/master/autosub.lua) did in order to make the script work out-of-the-box, instead of requiring user to write down his subliminal path?

Another way could be using `subliminal = (io.popen('which subliminal'):read("*a")):sub(1, -2)` though `popen()` is system dependent and is not available on all platforms.

**Comment by DavidDeprost** [comment] 2019-08-09 22:40
Actually, I do use `utils.subprocess()`, but this has nothing to do with making the path work without being specified.

Note that vayan's script will only work when you launch mpv from the terminal, since he hardcodes `subliminal` as executable. The terminal will be able to resolve this to the correct executable, but mpv's `subprocess()`  will not. This means the script will fail when mpv was opened by doubleclicking in a file explorer.

I don't think having to enter the subliminal path once on installation is all that bad.
Plus, as you correctly indicate, it would be difficult to automate path retrieval in a cross-platform way.
Besides `popen()` being system dependent, Windows for example does not have the `which` command, which complicates matters even more.

Thank you for the feedback!

**Comment by John-Gee** [comment] 2021-05-15 12:36
Actually I'm finding, in part, the same issue:

> subliminal --debug download -l en "1917 (2019) [BLURAY-1080P].mkv"

errors

but

> subliminal --debug download -l en "1917 (2019) [BLURAY-1080P.mkv"

or

> subliminal --debug download -l en "1917 (2019) [BLURAY-1080P[.mkv"


work just fine, not sure why the closing bracket matters.

a  simple addition allows the script to works:

> a[#a + 1] = filename:gsub(']', '')

but then we also need a rename on the way out and it works fine!
